Repository tgo-mas/soulpet-back, pull requests merged in 2023-04, with the labels that each got.

#23 criação model de Produto
  database/produto.js
  package.json
Labels: enhancement

#25 ajuste model servico
  database/servico.js
Labels: enhancement

#26 criacao do model agendamentos
  database/agendamento.js
  database/servico.js
  index.js
Labels: enhancement

#27 add model pedido
  .env.example
  database/pedido.js
Labels: documentation, enhancement

#28 arrumar-bug-model-produtos
  database/produto.js
Labels: bug

#29 add rotas get em pedidos
  routes/pedidos.js
Labels: documentation, enhancement

#30 criada rota GET de servicos, ajuste no relacionamento de agendamento
  database/agendamento.js
  database/servico.js
  routes/servicos.js
Labels: enhancement

#31 add rota post em pedidos
  database/pedido.js
  index.js
  routes/pedidos.js
Labels: documentation, enhancement

#32 Rotas get produtos
  index.js
  routes/produtos.js
Labels: enhancement

#33 Post serviço
  database/servico.js
  routes/servicos.js
Labels: enhancement

#34 Corrigido rota GET/servicos/id
  routes/servicos.js
Labels: bug
